NikolaiVChr/f16

Nasal/AI_list.nas, Nasal/MissileView.nas, Nasal/fire-control.nas, f16-base.xml, gui/dialogs/config.xml, gui/dialogs/missile-view-select.xml, gui/dialogs/missile-view.xml
This is all we need to change to have a working missile view on an aircraft
=> Missile view

Models/Armament/Weapons/GBU-12/duorack-4.xml, Models/Armament/Weapons/GBU-12/duorack-6.xml, Models/Armament/Weapons/GBU-12/gbu-12.xml, Models/Armament/Weapons/GBU-12/trirack-3.xml, Models/Armament/Weapons/GBU-12/trirack-7.xml, Nasal/f16.nas
Correction of a bug in Triplerack/duorack display and light correction in nasal
=> Correction on loads

Models/Cockpit/Main/engine.xml
As the title says
Center the rotation by the center of the needle.
=> Cockpit: Fix rotation of engine instruments

Systems/autoflight.xml
=> Control: Correct error in AP Angle Rad Feeders

Systems/autoflight.xml
Removes the "bounce" on stick release at high mach
=> Control: Change drive delay for AP Pitch, to improve SS at high mach

Models/Cockpit/Avionics/MFD/mfd_left.xml, Models/Cockpit/Avionics/MFD/mfd_right.xml, Models/Cockpit/Instruments/adi.xml, Models/Cockpit/Instruments/hsi.xml, Systems/f16-electrical.xml, f16-base.xml
=> Elec: Add missing CSD between ADG Gen, EPU bugfix, change drop VAC to 100

Systems/f16-electrical.xml, f16-base.xml
=> Systems: Elec: Fix bad MAIN and STBY gen voltage, make ratio based CSD to fix some bugs, set electrical to cold and dark by default

f16-base.xml
Should fix the fatal error reported by Baham
=> Control: Fix a fatal error that I have not encountered

Systems/f16-electrical.xml, f16-base.xml
=> Systems: Make Battery Charge/Discharge work

Systems/zoom-views.xml, f16-base.xml
Adds my modifed version of onox's distance zooming system.
J
=> Sim: Add distance zooming for exterior views

Nasal/f16.nas, Systems/f16-electrical.xml, f16-base.xml
Didn't realize 84fd84e went in my repo -- that method charged/discharged far to fast due to a bad design.
J
=> System: Make battery charging and discharging work correctly

Models/Cockpit/Main/misc.xml, gui/dialogs/autoflight.xml, gui/dialogs/controlPanel.xml
Cherry-picked over my dialog fix from master, so no conflicts when merging this into master
J
=> newRadar: 3D Fixes

Systems/autoflight.xml, f16-base.xml
Fixes a bug where once speed increase, the roll angle increase also
=> Control: Make A/P bank hold respect bank limit PROPERLY

Nasal/pylons.nas
The name in the options must match the name in the type
=> Fix pylon tank selection problem.

Nasal/f16.nas, gui/dialogs/config.xml
Addresses concerns in issue #242
=> Replace Quick start with more genuine Auto start

Nasal/f16.nas, Systems/jsb-electrical.xml, f16-base.xml, states/approach.xml, states/cruise.xml, states/ramp.xml, states/running.xml
Simulate the EPU safety pin, preventing firing when starting engine.
=> EPU: Simulate safety pin

Nasal/MFD/MFD_main.nas, f16-base.xml
Fixed MFD button text colors when switching to dogfight mode and made the settings for range, radar coupling, and HSD position equal for both MFD's
=> HSD and MFD button fixes

Models/Cockpit/Instruments/asi.xml, f16-base.xml
and thereby setting a proper default value.
=> Complete import of safe speed bug into f16

f16-base.xml, gui/dialogs/autoflight.xml
As requested by @JMaverick16 
Kind Regards,
Josh
=> GUI: Add heading to dialog as requested

Nasal/failures.nas, Systems/jsb-hook.xml, f16-base.xml
Hook now has a chance of failing if engaged above 175kts. Fixes #520.
=> Systems: Implement hook failure above 175kts

Nasal/ded.nas, Nasal/steerpoints.nas
Allows the ability to save DES TOS data in DTC files. Supports loading old DTC files as well. Likewise, (theoretically) old f-16 versions should also be able to load this new DTC format, though they obiously won't have support for CRUS TOS
=> DED: Support saving DES TOS in DTC

Nasal/steerpoints.nas
Fixed CRUS TOS page formatting.
=> DED: Fix CRUS TOS page formatting
